# description: configuration ID
# type: string
# required: true
podId: Notion

# description: optional description for the pod
# type: string
# description: TODO

# description: export scope of the pod.
# type: string
# NOTE: When a setting is missing from this config, you will get a UI prompt to select a value for that setting while running the export pod. For this particular exportScope setting, if you would rather not be prompted and always have the same exportScope, simply uncomment the line below.
# exportScope: TODO

# description: type of pod
# type: string
# required: true
podType: NotionExportV2

# description: ID of the Notion Connected Service
# type: string
# required: true
connectionId: secret_PdR5FVoaEGbfbw3pWycwVp2DStfc5PXg3ZUVtd4xvPO

# description: ID of parent page in notion
# type: string
# required: true
parentPageId: Test